// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6AClKCe7C91DyWcVH6eI8OTZyHmFetGs',
    appId: '1:1005130341735:web:9ae2b04b2d367a7ee1e3c2',
    messagingSenderId: '1005130341735',
    projectId: 'quiz-ai-242b4',
    authDomain: 'quiz-ai-242b4.firebaseapp.com',
    storageBucket: 'quiz-ai-242b4.firebasestorage.app',
    measurementId: 'G-CGVXPCBGZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1boq7lbEdYB_wQKCTCDrYHTSsIpUexI',
    appId: '1:1005130341735:android:e0287a2c8b6304cbe1e3c2',
    messagingSenderId: '1005130341735',
    projectId: 'quiz-ai-242b4',
    storageBucket: 'quiz-ai-242b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNSMDcG5biz3Pp83jW4g-IUBX0uWP2zCY',
    appId: '1:1005130341735:ios:2b25ce18b44e804ee1e3c2',
    messagingSenderId: '1005130341735',
    projectId: 'quiz-ai-242b4',
    storageBucket: 'quiz-ai-242b4.firebasestorage.app',
    iosBundleId: 'com.kk.uiQuiz',
  );
}
